#!/usr/bin/env python3
"""Emit flat model.meta from model.json using stdlib json (no hand-rolled C JSON).

Usage:
  python3 tools/emit_model_meta.py ../export/ci-smoke/model.json ../export/ci-smoke/model.meta
"""
from __future__ import annotations

import json
import sys
from pathlib import Path


def main() -> int:
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} model.json model.meta", file=sys.stderr)
        return 2
    src = Path(sys.argv[1])
    dst = Path(sys.argv[2])
    data = json.loads(src.read_text(encoding="utf-8"))
    audio = data.get("audio", {})
    ctx = int(data["context_frames"])
    n_mels = int(audio.get("n_mels", data.get("n_mels", 80)))
    feats = int(data.get("input_features", ctx * n_mels))
    visemes = data.get("visemes", {})
    n_vis = int(data.get("n_visemes", len(visemes)))
    lines = [
        f"# generated by emit_model_meta.py from {src.name} — do not hand-edit",
        f"context_frames={ctx}",
        f"n_mels={n_mels}",
        f"input_features={feats}",
        f"n_visemes={n_vis}",
        f"sample_rate={int(audio.get('sample_rate', 16000))}",
        f"hop_length_samples={int(audio.get('hop_length_samples', 160))}",
        f"window_length_samples={int(audio.get('window_length_samples', 400))}",
        f"n_fft={int(audio.get('n_fft', 1024))}",
        f"fmin={float(audio.get('fmin', 50.0))}",
        f"fmax={float(audio.get('fmax', 8000.0))}",
    ]
    # id → name
    by_id: dict[int, str] = {}
    for name, idx in visemes.items():
        by_id[int(idx)] = str(name)
    for i in range(n_vis):
        lines.append(f"viseme_{i}={by_id.get(i, str(i))}")
    dst.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {dst}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
